services:
  twitch-online-notifier:
    image: ghcr.io/thelovinator1/twitch-online-notifier:latest
    container_name: twitch-online-notifier
    environment:
      - TWITCH_APP_ID=${TWITCH_APP_ID}
      - TWITCH_APP_SECRET=${TWITCH_APP_SECRET}
      - TWITCH_USERNAMES=${TWITCH_USERNAMES}
      - EVENTSUB_URL=${EVENTSUB_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
    restart: unless-stopped
    expose:
      - 8080
