[project]
name = "twitch-online-notifier"
version = "1.0.0"
description = "A simple bot that notifies a Discord webhook when a Twitch channel goes online."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "aiohttp",
  "discord-webhook[async]",
  "python-dotenv",
  "sentry-sdk",
  "twitchapi",
]


[tool.poetry]
name = "twitch-online-notifier"
version = "1.0.0"
description = "A simple bot that notifies a Discord webhook when a Twitch channel goes online."
authors = ["Joakim Hellsén <tlovinator@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiohttp = {version = "*"}
discord-webhook = {version = "*", extras = ["async"]}
python-dotenv = {version = "*"}
sentry-sdk = {version = "*"}
twitchapi = {version = "*"}

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry.scripts]
bot = "twitch_online_notifier.main:start"

[tool.ruff]
preview = true
line-length = 120
lint.select = ["ALL"]
lint.pydocstyle.convention = "google"
lint.isort.required-imports = ["from __future__ import annotations"]
lint.pycodestyle.ignore-overlong-task-comments = true
lint.ignore = [
  "missing-copyright-notice", # Checks for the absence of copyright notices within Python files.
  "undocumented-public-module",   # Checks for undocumented public module definitions.
  "undocumented-public-class",   # Checks for undocumented public class definitions.
  "undocumented-public-package",   # Checks for undocumented public package definitions.
  "undocumented-public-nested-class",   # Checks for undocumented public class definitions, for nested classes.
  "undocumented-public-init",   # Checks for public __init__ method definitions that are missing docstrings.
  "commented-out-code", # Checks for commented-out Python code.
  "line-contains-todo", # Checks for "TODO" comments.

  # Conflicting lint rules when using Ruff's formatter
  # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  "missing-trailing-comma", # Checks for the absence of trailing commas.
  "prohibited-trailing-comma", # Checks for the presence of prohibited trailing commas.
  "docstring-tab-indentation",   # Checks for docstrings that are indented with tabs.
  "triple-single-quotes",   # Checks for docstrings that use '''triple single quotes''' instead of """triple double quotes""".
  "indentation-with-invalid-multiple",   # Checks for indentation with a non-multiple of 4 spaces.
  "indentation-with-invalid-multiple-comment",   # Checks for indentation of comments with a non-multiple of 4 spaces.
  "over-indented",   # Checks for over-indented code.
  "single-line-implicit-string-concatenation", # Checks for implicitly concatenated strings on a single line.
  "multi-line-implicit-string-concatenation", # Checks for implicitly concatenated strings that span multiple lines.
  "bad-quotes-inline-string",   # Checks for inline strings that use single quotes or double quotes, depending on the value of the lint.flake8-quotes.inline-quotes option.
  "bad-quotes-multiline-string",   # Checks for multiline strings that use single quotes or double quotes, depending on the value of the lint.flake8-quotes.multiline-quotes setting.
  "bad-quotes-docstring",   # Checks for docstrings that use single quotes or double quotes, depending on the value of the lint.flake8-quotes.docstring-quotes setting.
  "avoidable-escaped-quote",   # Checks for strings that include escaped quotes, and suggests changing the quote style to avoid the need to escape them.
  "tab-indentation",   # Checks for indentation that uses tabs.
]

[tool.pytest.ini_options]
python_files = ["test_*.py"]
