name: Docker

on:
  schedule:
    - cron: "27 6 * * *"
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
env:
  EVENTSUB_URL: ${{ secrets.EVENTSUB_URL }}
  TWITCH_APP_ID: ${{ secrets.TWITCH_APP_ID }}
  TWITCH_APP_SECRET: ${{ secrets.TWITCH_APP_SECRET }}
  TWITCH_USERNAMES: ${{ secrets.TWITCH_USERNAMES }}
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Download the repository
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - uses: docker/setup-buildx-action@v3
      
      # Set up Python 3.12
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      # Install Poetry
      - run: pipx install poetry

      # Install dependencies
      - run: poetry install
        
      # Run tests
      - run: poetry run pytest
        
      # Login to GitHub Container Registry
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Build and push
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/thelovinator1/twitch-online-notifier:latest
